# Data preparation for further analysis (part 4 of 4)

# Author: kirilboyanovbg[at]gmail.com
# Last meaningful update: 26-03-2024

# In this script, we import historical data & future predictions for sales price.
# Then, we add some calculated columns that are needed for the Streamlit app.
# The data is then exported to the 'Output data' folder.


# Setting things up ====

# Importing relevant packages
library(tidyverse)
library(arrow)


# Importing data generated by other scripts ====

# Importing clean historical data & future predictions
PredictedSalesAndIncome <-
  read_parquet("Temp data/PredictedSalesAndIncome.parquet")

# Importing macroeconomic data
MacroDataIMF <- read_parquet("Temp data/MacroDataIMF.parquet") %>%
  select(Year, GDP)


# Adding national averages to the data ====

# Note: the national averages will be based on actual sales data only,
# whereas the income will include all municipalities regardless of sales
# data availability
NationalAverages <- PredictedSalesAndIncome %>%
  filter(PriceType != "Estimated price") %>%
  group_by(Year) %>%
  mutate(AvgSalesPrice = mean(AvgSalesPrice, na.rm = TRUE)) %>%
  ungroup() %>%
  distinct(Year, .keep_all = TRUE) %>%
  mutate(AvgDisposableIncomeTotal = NationalDisposableTotalAvg,
         Municipality = "National average")

# Appending the national averages to the municipality-level data
FinalSalesAndIncome <-
  plyr::rbind.fill(PredictedSalesAndIncome, NationalAverages)


# Adding custom calculated columns ====

# Adding calculated columns related to housing affordability
FinalSalesAndIncome <- FinalSalesAndIncome %>%
  mutate(
    M2AffordedTotal = AvgDisposableIncomeTotal / AvgSalesPrice,
    M2AffordedMen = AvgDisposableIncomeMen / AvgSalesPrice,
    M2AffordedWomen = AvgDisposableIncomeWomen / AvgSalesPrice,
    YearsoBuy50M2Total = 50 / M2AffordedTotal,
    YearsoBuy50M2Men = 50 / M2AffordedMen,
    YearsoBuy50M2Women = 50 / M2AffordedWomen
  )

# Calculating indexed prices for each municipality
# Note: the "AvgSalesPriceIdx" index includes both actual & imputed sales prices
FinalSalesAndIncome <- FinalSalesAndIncome %>%
  group_by(Municipality) %>%
  mutate(BaseYearForMncp = min(Year, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(BaseAvgPrice = ifelse(Year == BaseYearForMncp,
                               AvgSalesPrice,
                               NA)) %>%
  group_by(Municipality) %>%
  mutate(BaseAvgPrice = mean(BaseAvgPrice, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(AvgSalesPriceIdx = AvgSalesPrice / BaseAvgPrice) %>%
  select(-BaseYearForMncp,-BaseAvgPrice)

# Calculating affordability indices for each municipality
# Note: the "AvgM2AffordedIdx" indices includes both actual & imputed sales prices
FinalSalesAndIncome <- FinalSalesAndIncome %>%
  group_by(Municipality) %>%
  mutate(BaseYearForMncp = min(Year, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(
    BaseAvgM2AffordedTotal = ifelse(Year == BaseYearForMncp,
                                    M2AffordedTotal,
                                    NA),
    BaseAvgM2AffordedMen = ifelse(Year == BaseYearForMncp,
                                  M2AffordedMen,
                                  NA),
    BaseAvgM2AffordedWomen = ifelse(Year == BaseYearForMncp,
                                    M2AffordedWomen,
                                    NA)
  ) %>%
  group_by(Municipality) %>%
  mutate(
    BaseAvgM2AffordedTotal = mean(BaseAvgM2AffordedTotal, na.rm = TRUE),
    BaseAvgM2AffordedMen = mean(BaseAvgM2AffordedMen, na.rm = TRUE),
    BaseAvgM2AffordedWomen = mean(BaseAvgM2AffordedWomen, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    AvgM2AffordedTotalChange = (M2AffordedTotal - BaseAvgM2AffordedTotal) /
      BaseAvgM2AffordedTotal,
    AvgM2AffordedMenChange = (M2AffordedMen - BaseAvgM2AffordedMen) /
      BaseAvgM2AffordedMen,
    AvgM2AffordedWomenChange = (M2AffordedWomen - BaseAvgM2AffordedWomen) /
      BaseAvgM2AffordedWomen
  ) %>%
  mutate(
    AvgM2AffordedTotalChange = round(100 * AvgM2AffordedTotalChange, 1),
    AvgM2AffordedMenChange = round(100 * AvgM2AffordedMenChange, 1),
    AvgM2AffordedWomenChange = round(100 * AvgM2AffordedWomenChange, 1)
  ) %>%
  select(
    -BaseYearForMncp,-BaseAvgM2AffordedTotal,-BaseAvgM2AffordedMen,-BaseAvgM2AffordedWomen
  )

# Formatting data types, sorting in the correct order, etc.
FinalSalesAndIncome <- FinalSalesAndIncome %>%
  mutate(
    Year = as.integer(Year),
    PriceTypeGroup = ifelse(PriceType == "Predicted price", "Prediction", "Historical")
  ) %>%
  arrange(Municipality, Year)


# Creating separate df with indices only ====

"
Designed for use in the Streamlit app, where showing indexed numbers over time
would be a cool way to compare the development in the national economy to that
of the local one (proxied by the local disposable income) as well as to that of
the sales prices.
"

# Selecting the already calculated sales price indices and disposable income
IndexedDevelopment <- FinalSalesAndIncome %>%
  select(Year,
         Municipality,
         AvgSalesPriceIdx,
         AvgDisposableIncomeTotal)

# Adding data on the national GDP
IndexedDevelopment <- IndexedDevelopment %>%
  left_join(MacroDataIMF, by = "Year")

# Adding indices for local disposable income and GDP
IndexedDevelopment <- IndexedDevelopment %>%
  group_by(Municipality) %>%
  mutate(BaseYearForMncp = min(Year, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(
    BaseAvgDispIncome = ifelse(Year == BaseYearForMncp,
                               AvgDisposableIncomeTotal,
                               NA),
    BaseGDP = ifelse(Year == BaseYearForMncp,
                     GDP,
                     NA)
  ) %>%
  group_by(Municipality) %>%
  mutate(
    BaseAvgDispIncome = mean(BaseAvgDispIncome, na.rm = TRUE),
    BaseGDP = mean(BaseGDP, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(AvgDispIncomeIdx = AvgDisposableIncomeTotal / BaseAvgDispIncome,
         GDPIdx = GDP / BaseGDP) %>%
  select(-BaseYearForMncp,
         -BaseAvgDispIncome,
         -BaseGDP,
         -GDP,
         -AvgDisposableIncomeTotal)


# Converting the df into the long format (easier to plot in plotly)
IndexedDevelopment <- IndexedDevelopment %>%
  pivot_longer(cols = c("AvgSalesPriceIdx", "AvgDispIncomeIdx", "GDPIdx")) %>%
  rename(Indicator = name, Value = value) %>%
  mutate(
    Indicator = case_when(
      Indicator == "AvgSalesPriceIdx" ~ "Avg sales price",
      Indicator == "AvgDispIncomeIdx" ~ "Avg disposable income",
      Indicator == "GDPIdx" ~ "National GDP"
    )
  )


# Exporting the data for further analysis ====

# Exporting combined dataset to use in e.g. the Streamlit app
write_parquet(FinalSalesAndIncome,
              "Output data/FinalSalesAndIncome.parquet")

# Exporing the indexed dataset for similar use
write_parquet(IndexedDevelopment, "Output data/IndexedDevelopment.parquet")

# Printing a notice to the user
print("Note: Data preparation for Streamlit successfully completed.")
print("The data have been successfully exported to the 'Output data' folder.")
